---
env:
  AWS_DEFAULT_REGION: ap-southeast-2

steps:
  - label: ":cargo: Prepare to build"
    command: env | grep AWS

  - label: ":rocket: Deploy"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::094447749694:role/role-sts-oculo-continuous-integration"
    command: aws s3 sync . s3://swagger.oculo.com.au/ --delete --acl public-read